### ISSUE TITLE
Setting root password does not seem to work

### ISSUE THREAD

**Issue by probonopd** [probonopd/temp-installer-gui#1]
https://github.com/probonopd/temp-installer-gui/blob/a52fa0c75668a4db03b538af025a260046160fcb/frontend/furybsd-install#L100

is at fault? I seem to be unable to log in as root in the GUI login window using the root account.

**Comment by pkgdemon** [comment]
It’s possibly the display manager not allowing root login.  A good test would be simply entering su - after a normal user login to switch to root user or control alt f2 if the chosen display manager and window manager allow it.

**Comment by probonopd** [comment]
Noob question: How does one see, in FreeBSD, whether a password has been set for the root user? (Not in `/etc/passwd` I figured...)

**Comment by probonopd** [comment]
Disabling direct root login; users in the wheel group can use sudo/doas instead.

Makes installation one step shorter and is more like other common desktop OSes.
